### ISSUE TITLE
renders_test failed

### ISSUE THREAD

**Issue by qjebbs** [tango-contrib/renders#1]
包里自带的测试，`TestRender22` 和 `TestRender6` 都失败了。后者是保存的换行符的原因，检查`\r\n`就PASS了。前者比较疑惑。

`Render22Action`有个实现了`afterBuf func(string, io.Reader)`，调用的语句是：

    if r.afterBuf != nil {
        r.afterBuf(name, rd)
        buf.Reset()
    }

所以作者应该意识到了，读取buf，会“清空/部分清除”它的数据，在代码里又`reset`了一次。所以返回的buf是空的，测试时要求非空就失败了。

我可能不了解这么做的用意，是不是可以直接实现 `afterBuf func(string,*bytes.Buffer)`，甚至是`afterBuf func(string,string)` 呢？又或者要保持现有接口：`buf2 := bytes.NewBuffer(buf.Bytes())`，再传递出来。

**Comment by lunny** [comment]
我这边环境运行TestRender6没有失败：
Mac OSX 10.11.6
Go 1.7

**Comment by qjebbs** [comment]
![image](https://cloud.githubusercontent.com/assets/16953333/17954551/475c6dd4-6aae-11e6-96ec-3010c74fd321.png)

可能是MAC做了什么处理吧。用十六进制编辑模式，可以看到文件里确实保存的是`\r\n`。修改了这个，WIN上测试就通过了。
